main:
  - name: Home
    url: /#home
    weight: 10
  - name: Research
    url: research/
    weight: 20
  - name: Media
    url: media/
    weight: 30
  - name: Publications
    url: /#papers
    weight: 40
  - name: Contact
    url: /#contact
    weight: 50
  - name: CV
    url: media/SGK-CV.pdf
    weight: 60
